addons:
  ssh_known_hosts: hednowley.synology.me:169

services:
  - postgresql
  - docker

env:
  - GO111MODULE=on

before_deploy:
  - openssl aes-256-cbc -K $encrypted_8c047e66c105_key -iv $encrypted_8c047e66c105_iv -in ../deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

jobs:
  include:
    - language: go
      go:
        - 1.12.x

      before_install:
        - cd go
        - go get github.com/mattn/goveralls

      before_script:
        - psql -c "create user sound with password 'sound';" -U postgres
        - psql -c "create database sound_test owner sound;" -U postgres

      script:
        - "$GOPATH/bin/goveralls -service=travis-ci"

      deploy:
        provider: script
        cleanup: false
        script: ./linux_dsm_build.sh &&
          ssh admin@hednowley.synology.me -p 169 "if ( sudo status sound | grep start ); then sudo stop sound; fi" &&
          scp -P 169 ./sound  admin@hednowley.synology.me:/volume1/other/soundDir/ &&
          ssh admin@hednowley.synology.me -p 169 "sudo start sound"

    - language: node_js
      node_js:
        - 12

      before_install:
        - cd elm

      script:
        - echo "skipping tests"

      deploy:
        provider: script
        cleanup: false
        script: yarn run build:prod && scp -P 169 ./dist/*  admin@hednowley.synology.me:/volume1/other/soundDir/static
